### PR TITLE
Init plugin generate

### PR DESCRIPTION
**Pull request by dbuzhorkaa**

### CODE REVIEW

**Comment by dbuzhorkaa** [comment]
Yes, we were thinking about cron job on Travis CI to perform generation on schedule for example once a week, because script needs to download 7Gb. What do you think?

**Comment by bdmogal** [comment]
Hmmm, I do not know travisCI very well. However, can't the regeneration be done as a separate build target? So only when we want, we run an additional build step that also regenerates the plugin reference? If that step is not run, it re-uses whatever exists?

**Comment by dbuzhorkaa** [comment]
We can create separate branch and setup regeneration in different `.travis.yml` file.

**Comment by bdmogal** [comment]
Let's think about the build process for this. @dbuzhorkaa can you resolve the conflicts here so I can merge?

**Comment by dbuzhorkaa** [comment]
@bdmogal added support for plugins blacklist. Also added checks to skip downloads

**Comment by bdmogal** [comment]
@dbuzhorkaa can you please fix the conflicts so I can merge this?

**Pull request merged**
