### PR TITLE
Fix texts issue 2

### PR DESCRIPTION
**Pull request by dbuzhorkaa**

### CODE REVIEW

**Comment by bdmogal** [comment]
The following texts should be left aligned:
1. Why CDAP
2. Get Started - all 3 sets of cards on both Cloud and On Prem tabs
3. Pipelines benefits

**Comment by leacd** [comment]
If we are reducing the number to 4 cards per row, the width of the individual cards should increase to fill the space. Please use the 4 cards pattern we use in the home page.

**Comment by dbuzhorkaa** [comment]
@bdmogal @leacd done. Please check

**Comment by bdmogal** [comment]
@dbuzhorkaa can you fix the merge conflict?

**Comment by bdmogal** [comment]
Also, @dbuzhorkaa the alignment of the plugins looks good. Will the description of the plugins come in a separate PR?

**Comment by dbuzhorkaa** [comment]
@bdmogal yes, if you don't mind I will provide plugins alignment in scope of #48

**Comment by bdmogal** [comment]
You mean the description of plugins right? Yes, that's fine. Let's fix  https://github.com/cdapio/website/pull/47#pullrequestreview-226927643 in this PR though.

**Comment by dbuzhorkaa** [comment]
Fixed plugin description.

**Comment by bdmogal** [comment]
@dbuzhorkaa the description LGTM. Can you please address https://github.com/cdapio/website/pull/47#pullrequestreview-226927643

**Comment by dbuzhorkaa** [comment]
@bdmogal working on it

**Comment by dbuzhorkaa** [comment]
done. please check

**Comment by bdmogal** [comment]
@dbuzhorkaa Something looks really wrong here in terms of alignment - 
image

**Comment by bdmogal** [comment]
Is the Reduced complexity and Increased flexibility text correctly aligned? Also, the descriptions should be vertically aligned with each other, right?

**Comment by dbuzhorkaa** [comment]
done

**Pull request merged**
