### PR TITLE
Move styles to custom theme

### PR DESCRIPTION
**Pull request by dbuzhorkaa**

### CODE REVIEW

**Comment by bdmogal** [comment]
@dbuzhorkaa I'm getting a deploy failed error:

image

**Comment by dbuzhorkaa** [comment]
@bdmogal, I'm looking into this.

**Comment by dbuzhorkaa** [comment]
@bdmogal, problem fixed. Deploy preview available here https://deploy-preview-8--elated-elion-bf1a8d.netlify.com/

**Comment by dbuzhorkaa** [comment]
Regarding formatting we can automate this with precommit hook and [prettier](https://prettier.io/).
To setup precommit hook we can use node.js package (husky)[https://github.com/typicode/husky]. Hooks will setup after installing node dependencies.

**Comment by bdmogal** [comment]
yes, let's do that. Will you do that in a separate PR? I'll merge this, since it looks ok.

**Pull request merged**
