### PR TITLE
Change texts for get started page

### PR DESCRIPTION
**Pull request by dbuzhorkaa**

### CODE REVIEW

**Comment by dbuzhorkaa** [comment]
@bdmogal Production section for **On Cloud?**

**Comment by bdmogal** [comment]
Both. I've added the texts in #42

**Comment by dbuzhorkaa** [comment]
I see text for On Premise for production here #38, but for cloud it's empty. Probably I miss something

**Comment by bdmogal** [comment]
@dbuzhorkaa no you were right. I've updated it.

Also, can we align the descriptions on the production cards for cloud?

**Comment by dbuzhorkaa** [comment]
done. Please check. Text alignment will be fixed in other pull request.

**Comment by dbuzhorkaa** [comment]
done. Please recheck

**Comment by bdmogal** [comment]
@dbuzhorkaa is this section going to be fixed later?

image

**Comment by dbuzhorkaa** [comment]
@bdmogal, yes. Text alignment goes in #47

**Comment by bdmogal** [comment]
Yes, but buttons, the text for linux above, etc also, right? Or can we add the text for linux in this PR?

``CDAP is available as a standalone package to install and run locally, so you can get started immediately on experimenting with data applications on your laptop or desktop.``

**Comment by dbuzhorkaa** [comment]
@bdmogal this is how it looks from another PR:

image

**Comment by dbuzhorkaa** [comment]
```
CDAP is available as a standalone package to install and run locally, so you can get started immediately on experimenting with data applications on your laptop or desktop.
```

Added as description for Linux / Mac card

**Pull request merged**
